 <footer class="footer text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#"><img class="img-back" src="assets/back_top.png"></a>
        </p>
        <p class="float-left">2018 S.S.S. &copy; all rights reserved.</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="bootstrap-4.1.1/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="bootstrap-4.1.1/assets/js/vendor/popper.min.js"></script>
    <script src="bootstrap-4.1.1/dist/js/bootstrap.min.js"></script>
    <script src="bootstrap-4.1.1/assets/js/vendor/holder.min.js"></script>
  </body>
</html>
